@extends('layout.laman_template')

@section('title', 'Ketentuan & Kebijakan Privasi')

@section('container')
<div class="container">
    {{-- <span>{{ Breadcrumbs::render('kkp') }}</span> --}}
    <a href="" class="mb-3">
        <img src="{{ asset("assets/img/1081458.jpg") }}" class="img-fluid rounded mb-3">
    </a>
    <h5>Ketentuan dan Kebijakan Privasi</h5>
    <p>Terima kasih telah menggunakan layanan KARYAPARLEMEN.COM. Perlu diperhatikan dengan menggunakan layanan ini, Anda menyepakati aturan dan ketentuan penggunaan layanan ini.</p>
    <p>Anda setuju dan mengikuti atau tunduk pada prosedur penggunaan layanan yang tersedia untuk Anda (end users), tunduk pada aturan perundang-undangan yang berlaku, dan sewaktu-waktu layanan dapat ditangguhkan atau dihentikan apabila dalam pemanfaatan layanannya terjadi pelanggaran ketentuan penggunaan layanan atau aturan hukum yang berlaku. Anda dapat memanfaatkan layanan yang disediakan menggunakan fasilitas atau antar-muka dan panduan yang telah disediakan, dan tidak dibenarkan mengakses layanan dengan metode dan antar-muka selain yang telah disediakan. Akses layanan kumparan dirancang untuk mudah diakses melalui gawai bergerak. Jangan menggunakan layanan dengan cara yang dapat mengganggu Anda mematuhi prosedur atau aturan keselamatan berlalu-lintas.</p>
    <p>Kepemilikan hak kekayaan intelektual informasi atau konten yang disajikan dalam layanan kumparan tetap berada penciptanya, antara lain kumparan sebagai korporasi, pihak ketiga yang bekerja saja dengan kumparan, atau pengguna (user generated content) yang sepakat mempublikasikan ciptaannya dalam layanan Kumparan.</p>
    <p>Menggunakan layanan kumparan tidak berarti memindahkan kepemilikan hak cipta konten atau informasi yang Anda akses. Anda dilarang menggunakan informasi selain yang dimaksudkan oleh layanan KARYAPARLEMEN.com, kecuali Anda memperoleh ijin penggunaan oleh pemegang hak ciptanya.</p>
    <p>Layanan kumparan menampilkan konten dan informasi pihak ketiga yang bekerja sama dengan kumparan. Konten-konten tersebut adalah tanggung-jawab pemegang hak ciptanya atau yang membuatnya tersedia. kumparan akan melakukan upaya terbaik untuk melakukan review, mengevaluasi atau menghilangkan konten/informasi yang ditayangkan apabila melanggar kebijakan penggunaan atau aturan hukum yang berlaku. Keputusan untuk mengkonsumsi informasi atau menggunakan layanan kumparan sepenuhi menjadi diskresi Anda, sebagai pengguna.</p>
    <p>penggunaan layanan, KARYAPARLEMEN.com mungkin akan mengirimkan pengumuman layanan, pesan atau informasi administrasi atau yang lainnya. Anda dapat mematikan (op-out) pilihan fitur komunikasi tersebut.</p>
                                    
    <p>Saat menggunakan layanan kumparan Anda mungkin akan diminta untuk mengidentifikasi diri Anda agar kumparan dapat mengoptimalkan layanan untuk Anda. Misalnya menyediakan informasi pilihan Anda, mengirimkan notifikasi topik-topik, isu-isu, kegiatan atau peristiwa yang mungkin Anda tertarik, dan tidak tertutup kemungkinan untuk membatasi akses konten dewasa. Untuk autentifikasi identifikasi diri, Anda dapat menggunakan layanan pengelolaan identitas atau akun pihak ke-tiga. Layanan yang tersedia saat ini untuk mengakses Layanan Kumparan adalah Google Account (https://myaccount.google.com/) dan Facebook Account .</p>
    <p>Aturan penggunaan layanan akun pihak ketiga tersebut diatur oleh masing-masing penyedia layanan. Silakan membaca informasi dan panduan pemanfaatan yang aman layanan tersebut di situs web layanan terkait.</p>
    <p>kumparan akan memberikan upaya terbaik untuk menjaga privasi dan melindungi hak-cipta sesuai dengan ketentuan dan perundang-undangan yang berlaku. Kebijakan privasi akan menjelaskan bagaimana kumparan mengumpulkan, dan mengelola informasi pribadi Anda.</p>
    <p>Beberapa fitur layanan kumparan memungkinkan Anda mengirim, menyimpan, mempublikasi, dan membagi-pakai konten atau informasi. Anda akan tetap memegang hak kekayaan intelektual semua material tersebut.</p>
    <p>saat mengunggah material tersebut melalui layanan kumparan, Anda memberikan (grant) kumparan hak dan lisensi untuk menyimpan, mengadaptasi, meredistribusi, membuat produk turunannya, dan memajangnya secara publik. Hak lisensi ini bertujuan agar kumparan dapat mengoperasikan, mempromosikan, dan meningkatkan layanan dan/atau mungkin menciptakan layanan baru. Lisensi ini akan tetap berlanjut meskipun Anda berhenti menggunakan layanan kumparan.</p>
    <p>kumparan disediakan melalui situs web atau piranti lunak yang dapat diunduh. Piranti lunak tersebut akan secara terus menerus ditingkatkan (update) dan mungkin akan secara otomatis mengupdate piranti lunak yang ada dalam gawai Anda. Anda mungkin harus menyesuaikan aturan pembaharuan otomatis (automatics update).</p>
    <p>kumparan akan senantiasa memperbaharui dan meningkatkan layanan. Kami mungkin akan menambah, mengurangi menangguhkan atau bahkan mematikan layanan tertentu.</p>
    <p>Anda dapat berhenti menggunakan Layanan kumparan kapan pun Anda putuskan. Kami akan sedih melihat Anda meninggalkan kami, dan kumparan mungkin akan membatasi atau bahkan menghentikan layanan untuk Anda. Karena akses ke data tersebut sangat penting, kumparan akan tetap berupaya menjaga ketersedian akses tersebut. Akan tetapi jika karena satu dan lain hal, kumparan harus menghentikan Layanan, maka kumparan akan memberikan pemberitahuan dan waktu yang cukup sebelum layanan dihentikan.</p>
    <p>Untuk mengoperasikan Layanan, kumparan mengerahkan teknologi dan tenaga-tenaga cakap yang secara profesional dan komersial cukup mumpuni untuk menyelenggarakan Layanan. Namun demikian, ada banyak faktor di luar kendali kumparan, dan oleh karenanya kumparantidak memberikan janji atau jaminan secara khusus terhadap Layanan. kumparan menyediakan layanan seperti apa adanya ("as is").</p>
    <p>Jika Anda menggunakan Layanan dengan tujuan atau atas nama bisnis atau untuk tujuan komersial, Anda sepakat dan menerima ketentuan ini. Dengan demikian ketentuan ini membebaskan kumparan dan seluruh mitra/pihak terkait dari semua klaim, tuntutan, ganti rugi dan biaya yang timbul terkait gangguan Layanan dan pelanggaran ketentuan ini. Untuk informasi lebih rinci tentang pemanfaatan layanan untuk tujuan komersial, silakan menghubungi komersial@kumparan.com</p>
    <p>Aturan penggunaan ini, berikut dengan pedoman media cyber, panduan komunitas, serta panduan dan/atau aturan lainnya berkaitan dengan Layanan dapat diubah dari waktu ke waktu dengan menambahkan aturan baru atau memodifikasi dan/atau menyesuaikan dengan perubahan layanan atau peraturan perundang-undangan yang berlaku oleh kumparan. Ketentuan-ketentuan tersebut berikut dengan perubahannya dari waktu ke waktu mengikat hubungan kumparan dengan Anda, dan selama Layanan ini tetap terus digunakan oleh Anda, maka Anda tetap tunduk pada aturan-aturan penggunaan Layanan tersebut. Tidak ada pihak ketiga lain yang mendapatkan hak dari hubungan ini.</p>
    <p>Bilamana ada sengketa yang tak dapat diselesaikan secara bilateral, maka resolusi akan di bawa ke lembaga pengadilan/arbitrasi yang memiliki yurisdiksi di mana badan hukum kumparan terdaftar.</p>
    <p>Privasi (Privacy Policy)<p>
    <p>Dengan menggunakan Layanan kumparan, Anda membagikan informasi pribadi dengan kami. Oleh karenanya, kumparan ingin Anda tahu bagaimana kumparan akan menyimpan dan menggunakan informasi yang Anda bagikan agar tetap menjaga privasi Anda.p</p>

    <p>Informasi yang dikumpulkan. Kami mengumpulkan informasi Anda agar dapat menyediakan layanan yang lebih baik, misalnya dari mana mengakses layanan, alamat surel, informasi yang Anda konsumsi, dan informasi-informasi yang lain. Ada dua macam informasi yang kami kumpulkan, yaitu:</p>
    <p>Informasi yang Anda berikan secara langsung dan tidak langsung, antara lain informasi akun Anda. kumparan menggunakan autentifikasi pihak ketiga, yaitu Google Account dan Facebook Account, maka kumparan akan mengumpulkan informasi terkait akun yang dibagikan oleh penyedia layanan, tentu saja atas persetujuan Anda, antara lain nama, alamat surel, jenis kelamin, foto, dan userID.</p>
    <p>Informasi yang direkam saat Anda menggunakan Layanan. Selama Anda menggunakan Layanan, kumparan akan merekam informasi aktivitas Anda, baik yang secara langsung atau menggunakan layanan pihak ketiga, misalnya topik yang dibaca, interaksi, umpan-balik, dan konten yang Anda bagikan.</p>

    <p>Informasi terkait akses gawai (device): kumparan merekam informasi terkait gawai yang Anda gunakan untuk mengakses Layanan kumparan, yaitu unique devide identification, model piranti keras, versi sistem operasi, operator jaringan, dan mungkin nomor telepon.</p>

    <p>Informasi log (catatan kejadian): Ketika Anda mengakses Layanan kumparan, maka server layanan kumparan akan mencatat informasi terkait akses Anda, antara lain alamat IP (Internet Protocol), sistem operasi, peramban (browser) atau aplikasi antar-muka untuk mengakses dan versinya, device event (crashed information, perangkat keras, pengaturan bahasa, url referral, tanggal dan waktu, identifikasi cookie, dan target url.</p>

    <p>Informasi lokasi (dengan teknologi GPS atau Cell Assisted GPS): Ketika akses Layanan berlangsung, kumparan menjacatat informasi aktual lokasi Anda melalui akses yang tersedia dalam sistem operasi piranti yang Anda gunakan.</p>

    <p>Penyimpanan lokal: Untuk memudahkan akses dan mempercepat response, kumparan mungkin akan mengakses dan menyimpan informasi ke penyimpanan lokal gawai (device) dengan mekanisme browser web storage (HTML5) dan application data caches.</p>

    <p>Cookies dan teknologi serupa: kumparan dan mitra-mitra kumparan akan menggunakan berbagai teknologi, termasuk cookies dan teknologi serupa untuk mencatat dan mengumpulkan informasi selama Anda menggunakan Layanan.</p>

    <p>Informasi yang dikumpulkan dan informasi yang kami dapatkan dari mitra kumparan, mungkin akan asosiasikan ke akun Anda, dan akan diperlakukan sebagaimana informasi pribadi Anda.</p>

    <p>Dengan informasi yang dikumpulkan dan hasil analisanya, kumparan menggunakannya untuk mengelola, meningkatkan dan menjaga Layanan kumparan, misalnya menyediakan layanan informasi kontekstual dan penawaran produk dan iklan komersial berdasarkan pola konsumsi, lokasi dan informasi spesifik Anda lainnya; meningkatkan UX (user experience) Layanan; atau memantau kinerja konten/informasi yang disajikan.</p>
    <p>Anda bisa menghidupkan opsi untuk menghalangi peramban (browser) untuk menyimpan dan menyimpan identifikasi melalui cookies atau teknologi serupa, termasuk cookies dari Layanan kumparan, hal ini akan membuat sebagian besar fitur Layanan tidak dapat berfungsi.</p>
    <p>Pengkinian data pribadi Anda. Selama menggunakan Layanan kumparan, kami akan selalu berupaya menyediakan akses, agar Anda dapat melakukan ralat dan melakukan pengkinian data pribadi bilamana perlu. Akan tetapi kami mungkin akan menolak permintaan pengkinian yang berlebihan.</p>
    <p>Demi keamanan (menghindari kecelakaan akibat penghapusan tak terduga) dan/atau terkait kasus legal/hukum, kumparan akan tetap menyimpan salinan informasi pribadi yang diminta untuk dihapuskan. Salinan ini akan disimpan selama waktu yang dipandang perlu.</p>
    <p>Kami tidak akan membagikan informasi pribadi/personal Anda dengan pihak lain di luar kumparan, baik individu, organisasi, atau badan hukum komersial lain, kecuali:</p>
    <p>Dengan sepengetahuan dan ijin Anda. Ketika melakukannya, kumparan mengimplementasikan mekanisme op-in untuk menangkap persetujuan Anda.</p>
    <p>Dengan pihak yang terafiliasi kumparan atau mitra-kerja terpercaya untuk melakukan pemprosesan dan analisis eksternal terhadap proses-proses bisnis internal kumparan.</p>
    <p>Untuk alasan penegakan hukum. Akses pada informasi pribadi/personal Anda akan kami berikan kepada lembaga atau organisasi, untuk memenuhi proses penegakan hukum, proses pengadilan dan permintaan yang syah demi hukum dari pemerintah.</p>
    <p>kumparan mungkin akan membagikan informasi terkait pribadi/personal tak-kasat (non-personally identifiable information) secara publik atau dengan pihak ketiga, mitra produksi informasi ataupun mitra komersial.</p>
    <p>Untuk tujuan pemberitahuan atau komersial, kumparan dapat mengirimkan pesan atau informasi yang bersifat pengumuman, notifikasi, penawaran, promosi dan/atau material komersial lainnya kepada Anda, termasuk di dalamnya informasi tentang perubahan fitur Layanan serta penyesuaian keamanan.</p>
    <p>Tentang keamanan informasi pribadi/personal. Untuk menjaga informasi pribadi/personal yang ada dalam kumparan, kami akan memberikan upaya terbaik untuk mencegah akses dan pengubahan tanpa-hak (unauthorized alteration) atau pengungkapan dan penghancuran informasi tersebut. Sebagai upaya, kumparan mengimplementasikan enkripsi Layanan kumparan dengan SSL, kami menggunakan layanan otentikasi dari mitra dengan teknologi terbaik, menerapkan akses dan secara rutin melakukan peninjauan prosedur akses terhadap fasilitas penyimpanan dan komputasi kumparan.</p>
    </p>
</div>
@endsection